###
GET http://localhost:5129/locations

###
GET http://localhost:5129/locations/27

###
GET http://localhost:5129/locations/location/RC54

###
POST http://localhost:5129/locations
Content-Type: application/json

 {      
    "LocationId": "PH",
    "Container": "Rack",
    "Unit": "G",
    "UnitRow": "1",
    "Drawer": "1",
    "Overloaded": false,
    "Underfilled": false,
    "LocationEmpty": true
  }

###
PUT http://localhost:5129/locations/27
Content-Type: application/json

  {
    "Id": 27,
    "LocationId": "RA33",
    "Container": "Rack",
    "Unit": "A",
    "UnitRow": "3",
    "Drawer": "3",
    "Overloaded": true,
    "Underfilled": false,
    "LocationEmpty": false
  }

###
DELETE http://localhost:5129/locations/140
