
GET http://localhost:5129/legos

###
GET http://localhost:5129/legos/32000

###
POST http://localhost:5129/legos/
Content-Type: application/json

{
  "BrickId": "3024",
  "Description": "1x1 Plate",
  "Category": "Basic",
  "SubCategory": "Plate",  
  "Container": "Rack",
  "Unit": "A",
  "UnitRow": "7",
  "Drawer": "8",  
  "Color": "White",
  "NumAvailable": 6,
  "NumInUse": 0,
  "AltBrickId": "",
  "Overloaded": false,
  "Underfilled": false,
  "LocEmpty": false
}

###
GET http://localhost:5129/legos/owned

###
GET http://localhost:5129/legos/owned/13

###
GET http://localhost:5129/legos/owned/brick/1234

###
POST http://localhost:5129/legos/owned
Content-Type: application/json

{
  "BrickId" : "44589",
  "ColorId": 11,
  "NumAvailable": 0,
  "NumInUse": 4,
  "LocationId": "RB2RA114"
}

###
PUT http://localhost:5129/legos/owned/21
Content-Type: application/json

 {      
    "BrickId": "3345",
    "ColorId": 5,
    "NumAvailable": 15,
    "NumInUse": 4,
    "LocationId": "RB24"
  }

### 
DELETE http://localhost:5129/legos/owned/23

###
GET http://localhost:5129/colors

